name: Deploy hirehub to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # use your EC2 runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env on EC2
        run: |
          cat > ~/IFN636Assessment-2/Backend/.env <<EOL
          PORT=${{ secrets.PORT }}
          MONGO_URI=${{ secrets.MONGO_URI }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          EOL

      - name: Deploy Backend
        run: |
          cd ~/IFN636Assessment-2/Backend
          git pull origin main
          npm ci
          pm2 stop backend || true
          pm2 start server.js --name backend --update-env

      - name: Deploy Frontend
        run: |
          cd ~/IFN636Assessment-2/Frontend
          git pull origin main
          npm ci
          CI=false npm run build

      - name: Restart Nginx
        run: sudo systemctl restart nginx
